### ISSUE TITLE
how can add images in learnr 

### ISSUE THREAD

**Issue by rajkumarManiRaja** [rstudio/learnr#137]

**Comment by mine-cetinkaya-rundel** [comment]
You can use the `knitr::include_graphics` function in an R chunk. See the [03a-data-manip-filter](https://raw.githubusercontent.com/rstudio/learnr/master/examples/03a-data-manip-filter/03a-data-manip-filter.Rmd) example tutorial for sample usage.

**Comment by jjallaire** [comment]
You can also use a markdown image so long as it is located in the `images` directory, see https://rstudio.github.io/learnr/#external_resources

    ![](images/my-image.png)

**Comment by Wario84** [comment]
I was wondering if there is a way to add an image through the function quiz(...). So as an argument.

**Comment by schloerke** [comment]
```{r myques}
quiz(
	question("My Question",
		answer(
			htmltools::img(
				src = "https://pkgs.rstudio.com/gradethis/reference/figures/logo.png"
			), 
			correct = TRUE
		)
	)
)
```

![Screen Shot 2021-05-10 at 11 52 14 AM](https://user-images.githubusercontent.com/93231/117687843-3225bc80-b186-11eb-9f89-42ed0f6392ce.png)

**Comment by NinaCorrelAid** [comment]
I used both options but for both the preview just shows me a generic picture icon (file is found, looks fine in rmarkdown but disappears isn preview). Any ideas why?

**Comment by gadenbuie** [comment]
@NinaCorrelAid where is the image located and how are you adding it?

**Comment by NinaCorrelAid** [comment]
Hey there! Thanks for the quick reply!
I am saving the PNG locally inside the folder where my RMD is located. Executing here::here() gave me "/Users/ninahauser/rprojects/lernplattform", so I put the PNG there. However then I got a "File not found error". Hence, I had to put it inside of "/Users/ninahauser/rprojects/lernplattform/lernplattform". It is now found.
I then tried both options: 
a) ![DataUseCase](DataUseCase.png) - does not do anything in rendered but gives a fine looking preview in RMD
b) knitr::include_graphics("DataUseCase.png") - just gives me nothing.
Any leads?

**Comment by gadenbuie** [comment]
Please try storing the photo in a directory called `images/` next to the tutorial and referencing it using a relative file path, i.e. either as `![](images/DataUseCase.png)` or `knitr::include_graphics("images/DataUseCase.png")`.

**Comment by grover4** [comment]
Hi, So I am trying to run the learnr tutorials from the dsbox package on  Rstudio Workbench and we are seeing this error

Rendering tutorial in a temp folder since `learnr` does not have write permissions in the tutorial folder: /sw/ebpkgs/software/rgdal/1.4-8-foss-2020a-R-4.0.0/dsbox/tutorials/01-edibnb

and consequently there is a problem with the graphics file not being found. Any thoughts on whether the learnr package works differently on a server than say on my laptop (because this works just fine on my laptop). Rstudio Workbench is running version Rstudio ver 1.4.1717-3  and the version of R is 4.0.0.

Quitting from lines 36-37 (01-edibnb.Rmd) 
Error in knitr::include_graphics("images/madeleine-kohler-90Qn643Pq9c-unsplash.jpg") : 
  Cannot find the file(s): "images/madeleine-kohler-90Qn643Pq9c-unsplash.jpg"
Calls: sourceWithProgress ... withCallingHandlers -> withVisible -> eval -> eval -> <Anonymous>
Execution halted

**Comment by gato365** [comment]
Is there a way to store a logo on each page?

**Comment by lhami** [comment]
Is it a learnr constraint or a shiny constraint that the folder has to be called "images", specifically? It would be nice to be able to specify something like, say, img/ as the folder for consistency with the rest of the codebase I'm working on and the sake of not having to duplicate images. Is there a way to set the folders that the knit tutorial has access to in the options?
