### ISSUE TITLE
learnr and bookdown

### ISSUE THREAD

**Issue by davidmeza1** [rstudio/learnr#168]
Is is possible to use bookdown to combine a group of tutorials and not lose learnr functionality.

**Comment by schloerke** [comment]
The hard part is that you need a shiny backend to run learnr, where as bookdown is multiple, static rmardown files. 

I don't see this being implemented in the near future, but will keep the card open as hosting multiple learnr files seems fair.

**Comment by knachman** [comment]
I would be interested in this functionality as well. I'm creating a series of tutorials for my organization and it would be nice to combine them all into bookdown format.

**Comment by jienagu** [comment]
I would be interested in this functionality too. I am interested in documenting students' work into pdf or any other formats or have a widget for user to download their works. Bookdown might be a good option to fulfill this functionality.

**Comment by znmeb** [comment]
I'm looking into something like this - since there's a Shiny back end required, maybe `flexdashboard` would work as a learnr website creator.

**Comment by katiepress** [comment]
Flexdashboard would be fine too, the only thing I don't like about that is there isn't a way - or at least a reasonably simple way - that I've found to have the navbar on the side instead of the top? It just seems like a better workflow in a tutorial vs having to go up and pop the navbar open. That is one thing I like about the way the learnr tutorial output is set up, I just need more options for the heading levels on the table of contents, and preferably be able to collapse the toc as well.

It would be great to have a learnr output for shiny apps too where you could embed learnr chunks in your app just like a plot or whatever else. Or maybe there is a way to do that with htmlOutput or uiOutput already? 


(I'm knachman as well I just changed my username recently)

**Comment by RaymondBalise** [comment]
Add me to the list of people who would use this.  I would love to bundle all the tutorials for a class.

**Comment by LukasWallrich** [comment]
Yes, this would indeed be very helpful!

**Comment by vnijs** [comment]
+1 for this feature

**Comment by vnijs** [comment]
It is possible to have multiple rmarkdown documents with shiny run time in a website as in the example by @hugo-pa. This does not work with `shiny_prerendered` however due to https://github.com/rstudio/rmarkdown/issues/1576. Since that doesn't work at the moment, is it possible to have `learnr` use runtime `shiny` rather than `shiny_prerendered`?

https://github.com/hugo-pa/shiny_website_example

**Comment by vnijs** [comment]
One more ... could you embed `learnr` apps in a `shiny` website? This works with shiny + knitr currently (link below). Could `learnr` somehow piggy-back on the shiny environment it is already running in?

GitHub:  https://github.com/vnijs/shiny-site
Shinyapps.io: https://vnijs.shinyapps.io/shiny-site/

**Comment by acircleda** [comment]
I am curious if there has been a working example of combining `learnr` and `bookdown'` yet.  I too would like to combine them.

**Comment by coatless** [comment]
The closest I've seen to replicating this functionality requires leaving the `bookdown`/`learnr` vs. and deploying with other tools. c.f. 
1. an RMarkdown document powered by a binder instance by @cderv
    - https://rpubs.com/cderv/581740 ([Tweet Announcement](https://twitter.com/chrisderv/status/1235668163741839373))
2. a website outside of the `rmarkdown` framework.
    - https://course-starter-r.netlify.com/ ([Source](https://github.com/ines/course-starter-r))

**Comment by itsyaoyu** [comment]
+1 I'm also looking to add interactive examples in a bookdown textbook. This would greatly increase student engagement with the material!

**Comment by dtkaplan** [comment]
=1 not to jump on the bandwagon, but I also would find this helpful. I am working on sets of tutorials to cover a whole semester course.

**Comment by hgreatrex** [comment]
I would also find this useful if possible

**Comment by zief0002** [comment]
I echo the others in saying that this feature would be great to have.

**Comment by petzi53** [comment]
I share the desire to put interactive exercises into a book and also thought primarily of a solution with bookdown. 

But recently, I came across the very comprehensive tutorial of the OpenIntro project. [Introduction to Modern Statistics](https://openintrostat.github.io/ims-tutorials/) is showcasing another approach: It uses the `learnr` package itself to provide extensive textual explanations. The huge eight tutorials consist of several large Rmd files with many chapters and sections so that they form an (interactive) textbook on their own.

But there is still also [the textbook, written with bookdown](https://openintro-ims.netlify.app/) to provide a general introduction to statistics independently from R.

**Comment by johannes-titz** [comment]
I would also love to see this functionality. For now, I use an rmarkdown website with a navigation bar at the top to access seven different tutorials: https://rlernen.de/ -- Not ideal, but works.

**Comment by kcarnold** [comment]
This came up today in a department conversation; we'd also be interested in seeing this work.

Since the main blocker is the shiny connection, https://quarto.org/docs/blog/posts/2022-10-25-shinylive-extension/ plus https://github.com/georgestagg/webR could be an approach: run everything in the browser.

Another direction could be to see if learnr code chunks could be embeddable, e.g., using iframes.

**Comment by gadenbuie** [comment]
Distilling the advice in this conversation, for publishing a collection of tutorials I would recommend following the examples above:

1. The OpenIntro project – [Introduction to Modern Statistics](https://openintrostat.github.io/ims-tutorials/) – uses a website that organizes and links to many tutorials.
2. [Rlernen](https://rlernen.de/) uses an [R Markdown website](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html) and similarly links to many deployed tutorials.
3. The [Building Web Apps with Shiny](https://rstudio-education.github.io/shiny-course/) course also uses an R Markdown website to showcase learnr tutorials that are paired with Posit Cloud projects ([source repo](https://github.com/rstudio-education/shiny-course/)). Importantly, this course uses a custom navbar to link between modules (tutorials) of the course.

The above represent the current best practices and in my opinion do an excellent job of balancing the requirements for deploying learnr tutorials with the organizational needs of material that span more than one learning session.

**Comment by irudnyts** [comment]
If anyone still needs a workaround, I developed a small proof of concept: [https://github.com/irudnyts/jsquiz](https://github.com/irudnyts/jsquiz). Basically, this is like `{learnr}`'s MCQs that use only JavaScript and do not require a Shiny backend. 

I drafted this for internal purposes, but if anyone needs it, I'm happy to elaborate.

**Comment by coatless** [comment]
I would also add `{webexercises}` that covers a bit more options w/o a Shiny backend and works across both RMarkdown & Quarto: 

<https://psyteachr.github.io/webexercises/>

Source:

<https://github.com/PsyTeachR/webexercises>

You could also toy around with `quarto-webr` for crafting code exercises w/o Shiny:

<https://github.com/coatless/quarto-webr>

**Comment by irudnyts** [comment]
@coatless very cool! I wish to see that in the morning -- would save me a day 🙂

**Comment by johannes-titz** [comment]
Regarding the new suggestions it would be helpful to state whether R code can actually be run. Seems to be only the case for quarto-webr, but this looks very promising! The rest seems to be just for creating quizzes, right?

**Comment by hgreatrex** [comment]
This is great!  I would definitely be interested in knowing
more/elaboration Iegor, or trying out some of these ideas for the Spatial
Statistics course I'm teaching in the fall.


 Dr Helen Greatrex (pronouns: she/hers)
Assistant Professor in Remote Sensing and Geospatial Analysis
Department of Geography, Department of Statistics & Co-Hire of the
Institute for Computational and Data Sciences
201 Walker Building
University Park, PA 16802



*Learn more about the Rainbow Science Lab I lead here
<https://science.psu.edu/diversity-initiatives/rainbow-science-network>See
our acknowledgment of the lands Penn State stands on here:
<http://equity.psu.edu/acknowledgement-of-land>*
