### ISSUE TITLE
Can I Pass an Object to Next Exercise Chunk?

### ISSUE THREAD

**Issue by dudrnjs1391** [rstudio/learnr#170]
I executed this code. But, All chunk Separated and cant't inherited from previous chunk.
Can I use the data from the previous chunk to the next chunk?

* Make an Object and Check It
```
"```{r 2.1.data_create, exercise=TRUE}```"
```

```
"```{r 2.1.data_create-solution, exercise.setup="2.1.data_create-solution"}
tmp <- c(1,2,3)
```"
```

```
"```{r 2.2.data_plus, exercise=TRUE, ref.label="2.1.data_create-solution"}```"

```

```
"```{r 2.2.data_plus-solution}
tmp <- tmp+1
```"
```
### the result will be tmp = 2,3,4
<br>

```
"```{r 2.3.data_plus_plus, exercise=TRUE, ref.label="2.2.data_plus-solution"}```"
```

```
"```{r 2.3.data_plus_plus-solution}
tmp <- tmp+2
tmp
```"
```
### the result will be tmp = 4,5,6

**Comment by jjallaire** [comment]
That's correct. Each exercise chunk stands alone. This can definitely be an annoying limitation, however there are a few reasons why we do this:

1) So that users can run exercises in any order they wish;

2) So that exercises are "stateless" and can as a result run in a more scalable fashion (e.g. creating a farm of servers that just run exercies)

3) We automatically save the state of tutorials between runs (including outputs). It's cost prohibitive storage wise though to save the actual R objects (as they could be data frames of unbounded size) so the user just sees their outputs replayed. In this case the actual R state is lost and exercises depending on previous exercises would be broken.

The workaround is to create setup chunks that already have the "expected" values primed.
