### ISSUE TITLE
Support test-driven development style of questions and solutions

### ISSUE THREAD

**Issue by gvwilson** [rstudio/learnr#204]
(following discussion with @schloerke - please correct if I've misunderstood)

I want to be able to ask a learner to write some code and provide them with a set of assertions that the finished code has to pass that they can see, and another set that it also has to pass that they can't see. The first set helps clarify the exercise goals, and shows them what test-driven development looks like. The second set of checks (hidden from them) is necessary so that they don't just write "if inputs 1 then print solution 1, if inputs 2 then print solution 2".

My suggestion was to allow multiple `-check` blocks for each exercise and use `include=TRUE` and `include=FALSE` to control which the learner could see. @schloerke believes we can get the same effect with much less disruption by writing a slightly more sophisticated equivalent to `strict_check` and/or `grade_learnr`.

**Comment by garrettgman** [comment]
You could put the tests that the student sees in a regular knitr chunk that contains the `eval = FALSE` option (the tests will appear in a non-interactive chunk where the student can read them).

---

It sounds like the additional tests should be part of the grading scheme (i.e. there should be a test based check feature for learnr). I'm not sure if this feature should be baked into learnr or appear in an add on package, because it is focused on a subset of exercises: those that ask the student to define a function.

FWIW, this example is similar to the multiple choice question grading paradigm, which @schloerke is porting over to chunk exercises. That paradigm is focused on executable code (i.e. it executes the code and then matches the result to a message).

````
assert_that(is.nan(span(c(99))), msg = "Vector of length 1 has no span")
assert_that(span(c(4, 5)) == 1, msg = "Expected span of 1")
assert_that(span(c(5, 4)) == 1, msg = "Order should not matter")
assert_that(span(c(5, 5)) == 0, msg = "Spans can be zero")
````
