### ISSUE TITLE
Long quiz distractors start under radio button

### ISSUE THREAD

**Issue by petzi53** [rstudio/learnr#207]
Just an aesthetical issue: When the key or one of the distractors of a quiz is longer than one line on the screen then the text starts under the radio button. 

Is there a way to start the text beside the radio button – as in shorter questions – and to center the radio button vertically relating to the questions lines?

**Comment by schloerke** [comment]
The positioning has just been fixed in the master branch of learnr as the quizes are now mini shiny applications.  Please give it a test using the latest version and let me know if you run into any more issues:  `remotes::install_github("rstudio/learnr")`.

The width is being adjusted in #222 to 100%.  This should be merged shortly.
