### ISSUE TITLE
Export two functions: get_all_state_objects() and submissions_from_state_objects()

### ISSUE THREAD

**Issue by davidkane9** [rstudio/learnr#454]
get_all_state_objects() and submissions_from_state_objects() are handy functions. I use them in my [package of tutorials](https://github.com/PPBDS/primer.tutorials). But, because they are not exported, I need to ::: my way into them.

```r
        objs <- learnr:::get_all_state_objects(session)
        objs <- learnr:::submissions_from_state_objects(objs)
```
Could you export them so that this hack is not necessary? (Apologies if this is an uninformed request. I am new to much of this technology.)

Update: And learnr::read_request() as well.

**Comment by dtkaplan** [comment]
I echo this request. These functions are the foundation of Colin
Rundel's `{learnrhash}`, which I have become converted to. The purpose
there, and for me, is to take a snapshot of tutorial submissions for
students to hand in to receive a score on an assignment. In `{submitr}` I
was doing this by monitoring and storing the `{learnr}` event stream. The
problem with the event-stream approach is that the appearance to the
student (governed by the browser storing state) reflects all previous
sessions (since "Start Over"), whereas the event stream is ignorant of
anything before the present session..

A related request ... in my hacked up development version of `{learnr}`, I
store not just the most recent answer to tutorial questions but the
*history* of answers (since "Start Over"). These also are collected by
`learnr:::submissions_from_state_objects()`. This is useful for analyzing
misconceptions while still allowing the student to benefit from the custom
feedback from wrong answers to questions.

**Comment by doomlab** [comment]
I third this request! I am doing the same thing for my course packages, after checking out `learnrhash`.

**Comment by davidkane9** [comment]
Any thoughts on this from the maintainers? I could submit a PR since, I think, all we need is some @export calls in the documentation.

**Comment by schloerke** [comment]
@davidkane9 Yes please. This will make it easier

Thank you!

**Comment by davidkane9** [comment]
Consider the usage here:

https://github.com/PPBDS/primer.tutorials/blob/master/R/submission_functions.R

These tutorials were completed by 200 students this academic year. Next year, I expect 2,000 students to use them. 

My use is very similar to https://github.com/rundel/learnrhash/ and to some of the stuff that dtkaplan  has done.

The basic idea is that we all want to be able to do what we want with the text which students have typed into the tutorial.

**Comment by davidkane9** [comment]
> a better understanding of the desired goals

I can't speak for @dtkaplan or @mattblackwell or @rundel (see their [usages](https://github.com/search?q=learnr%3A%3A%3Aget_all_state_objects&type=code)), but I want to export everything associated with a student's completion of a tutorial into an object. (Then, I can do stuff with that material, like make a pdf, rds object or whatever.) That material should include the name of the tutorial, the questions in the tutorial (although I don't really need these) and (most importantly) everything character which student submitted to the tutorial. (It is OK if I can only get their last submissions. I don't need to see all attempted answers.)

Let me know if you want more details. This is not an emergency since my current hackery works fine. But it sure is ugly. I would also guess that the lack of this functionality decreases the pick up of the learnr package.

I typical teacher wants to  create a tutorial and make it easy for students to "submit" their answers via some school LMS or email, even if those answers are not graded automatically. Without the easy creation of an object (rds, PDF, whatever) that students can submit, tutorials are not nearly so helpful as they might otherwise be.

**Comment by doomlab** [comment]
I will echo @davidkane9 here - this is exactly my use case. I've written two packages using learnr tutorials:
- https://github.com/doomlab/learnSTATS/tree/master/inst/tutorials
- https://github.com/doomlab/learnSEM/tree/master/inst/tutorials

I am exporting these functions so I can print a report at the end of the tutorial that students can submit to our LMS. 

<img width="986" alt="image" src="https://user-images.githubusercontent.com/27783894/119732131-d033ab00-be45-11eb-9ad3-bfd6a9baaf10.png">

My functions are mostly copied ideas from `learnrhash` because I couldn't figure out the documentation from the `learnr` website how to export answers otherwise.
- https://github.com/doomlab/learnSEM/blob/master/R/encoder_logic.R
- https://github.com/doomlab/learnSEM/blob/master/R/server_context.R
- https://github.com/doomlab/learnSEM/blob/master/R/encoder_ui.R

**Comment by mattblackwell** [comment]
I have the same basic use case. I have a function that generates a Rmd file containing information about completion of the various exercises, whether they were skipped, etc. Here's the core code that creates the summary table that I put into the report:
```r
      # Set up parameters to pass to Rmd document
      objs <- learnr:::get_all_state_objects(session)
      skips <- learnr:::section_skipped_progress_from_state_objects(objs)
      subs <- learnr:::submissions_from_state_objects(objs)

      out <- tibble::tibble(
        id = purrr::map_chr(subs, "id"),
        answers = purrr::map_chr(subs, list("data", "answer"),
                                 .default = NA),
        checked = purrr::map_lgl(subs, list("data", "checked"),
                                 .default = NA),
        correct = purrr::map_lgl(subs, list("data", "feedback", "correct"),
                                 .default = NA)
      )
      out$attempted <- !is.na(out$answers) | out$checked
```

An API to generate these types of fined-grain summaries of the completion status would be sufficient for me at least. My recollection is hazy, but I think I got these ideas from the same sources as above.

**Comment by gadenbuie** [comment]
Thanks everyone for your comments. I think we've found a solution that will work for most of these use cases. We're now providing `get_tutorial_state()`, which provides a `shiny::reactiveValues()` list with a users's most recent submission for all questions and exercises, along with the submitted answer and its correctness. (See #562 for more details.) This state is recreated from stored state on tutorial load (if the questions and exercises are re-checked) and includes the most up to date results, as far as learnr knows about them.

To supplement the final missing piece — the tutorial ID found by calling `read_request()` — I've also added `get_tutorial_info()` which returns the tutorial identifiers. This value isn't reactive, but may change in the initialization lifecycle, so you'll have the best results if you call it as needed rather than once at session start.

Please feel free to open new issues or comment here with any questions/issues that come up!
