### ISSUE TITLE
get_tutorial_state() returning exercise states in order

### ISSUE THREAD

**Issue by NuoWenLei** [rstudio/learnr#570]
Hello,

I just wanted to start off saying that the newly introduced functions get_tutorial_state() and get_tutorial_info() has helped me tremendously.

I have a small suggestion regarding the order in which `get_tutorial_state()` returns exercises. `get_tutorial_state()` returns exercises in alphabetical order, however in my use case, I'd much prefer `get_tutorial_state()` to return exercise states in order of appearance in the tutorial.

Currently, I am using a workaround with `parsermd` to get all the labels of a tutorial and sorting them in that order, but it would save me a lot of trouble if the order could be changed by some kind of parameter.

Thank you!

**Comment by gadenbuie** [comment]
Unfortunately, both the tutorial state and the question/exercise caches are stored in environments rather than lists. One limitation of this approach is that R environments don't inherently have a notion of order:

```r
env <- new.env()
assign("b", 1, envir = env)
assign("a", 2, envir = env)
ls(env)
#> [1] "a" "b"
```

I do think it's reasonable to ask for the exercise and questions in order, so I'd like to accommodate this. For the cache, we can add an additional object to track the order of the questions/exercises. Where this gets slightly complicated is that we would need to alter `get_tutorial_state()` so that it returns a plain list rather than a `reactiveValues()` object when `label` is `NULL`. I don't think that's far from what most people would expect, and you could still take a reactive dependency on a single question/exercises by providing the `label`.

**Comment by schloerke** [comment]
> when `label` is `NULL`

learnr does not allow for `NULL` labels..., right?

https://github.com/rstudio/learnr/blob/769d2941d49411840fc598bbe3ef65f570842744/R/knitr-hooks.R#L520-L521

**Comment by gadenbuie** [comment]
Sorry, I meant that when the `label` argument of `get_tutorial_state()` is `NULL` we return the full state which was previously a `reactiveValues()` object but that will now be a list.

> Maybe instead of storing directly into an environment, store the value into an object within the environment?

This is my plan but we'll need to either intermingle questions and exercises in that object or if we keep them separate we'd need a third object to track their collective order. I'm thinking of taking the first option, but it does make the question and exercise `get_` functions a little more complicated.
