### ISSUE TITLE
Exercises in child documents

### ISSUE THREAD

**Issue by chendaniely** [rstudio/learnr#608]
It seem that when I put the `-solution` chunk into a child document, I get an error about "no solution provided".
If I put in the `-code-check` chunk into a child document, the "submit code" button disappears. Seems like `gradethis` doesn't pick up the child documents.
Maybe it's in the order of how the document is knited?

I'm personally using child documents to reduce the number of duplicate text for an experiment with 4 treatment arms. 2 of the arms look at using `gradethis` vs not using `gradethis`. The actual amount of code isn't a big deal at the moment, since most of the experiment is regular R markdown stuff for the coding exercises.

I haven't seen/worked on `gradethis` in years, and it's been vastly improved since. 👍 

<hr>

This works as expected. I put in a regular R chunk as the child document, and everything still works as expected.

`gt.Rmd` without `gradethis` child docs (see ex1 child document below):

`````
---
title: "Hello, Tutorial!"
output: learnr::tutorial
runtime: shiny_prerendered
description: "Welcome to learnr tutorials!"
---


```{r setup, include=FALSE}
library(learnr)
gradethis::gradethis_setup()
```

* Submit `1+1` to receive a correct grade.

```{r, child="c-ex1.Rmd"}
```

```{r exercise1-solution}
1+1
```
 
```{r exercise1-code-check}
grade_code()
```

`````

<hr>

This does not work as expected. I expected this to work as if I was not using child documents. But it seems the `gradethis` portion does not get picked up at all when they are in child documents.

`gt.Rmd` with `gradethis` child docs:

`````
---
title: "Hello, Tutorial!"
output: learnr::tutorial
runtime: shiny_prerendered
description: "Welcome to learnr tutorials!"
---


```{r setup, include=FALSE}
library(learnr)
gradethis::gradethis_setup()
```

* Submit `1+1` to receive a correct grade.

```{r, child="c-ex1.Rmd"}
```

```{r, child="c-ex1-solution.Rmd"}
```

```{r, child="c-ex1-code-check.Rmd"}
```

`````

`c-ex1.Rmd` file:

`````
```{r exercise1}
#| exercise = TRUE


```
`````

`c-ex1-solution.Rmd` file
`````
```{r exercise1-solution}
1+1
```

`````

`c-ex1-code-check.Rmd` file:
`````
```{r exercise1-code-check}
grade_code()
```

`````

**Comment by gadenbuie** [comment]
@chendaniely On second read, I see the issue. The problem with using child documents in this way

````
```{r, child="c-ex1.Rmd"}
# holds exercise1 chunk
```

```{r, child="c-ex1-solution.Rmd"}
# holds exercise1-solution chunk
```

```{r, child="c-ex1-code-check.Rmd"}
# holds exercise1-code-check chunk
```
````

is that when the rmarkdown/knitr process arrives at the first child chunk, it discovers `exercise1`. At that point, it'll go looking for the supporting chunks, such as `exercise1-solution`.

In the normal execution model, where the chunks are all defined in the same document, knitr has access to other chunks in the document, including those that haven't been evaluated yet. But when using child chunks, the child documents are read sequentially and added into the document.

This means that you need to do two things to make the  piece-wise child document model work:

1. Include all supporting chunks _first_ before the exercise chunk.

   ````
   ```{r, child="c-ex1-solution.Rmd"}
   # holds exercise1-solution chunk
   ```
   
   ```{r, child="c-ex1-code-check.Rmd"}
   # holds exercise1-code-check chunk
   ```
   
   ```{r, child="c-ex1.Rmd"}
   # holds exercise1 chunk
   ```
   ````

2. Now there's a reverse chicken and egg problem. Because the supporting chunks exist in the document before the official **exercise** chunk, you will need to explicitly include the `echo = FALSE` and `eval = FALSE` chunk options in the chunks in the child docs.

   ````
   ```{r exercise1-code-check, eval=FALSE, echo=FALSE}
   grade_code()
   ```
   ````

Hope that helps! This sounds like a very interesting and novel use of learnr and gradethis and we'd love to hear how your experiments go!

**Comment by chendaniely** [comment]
swapping the order and adding the extra chunk params fixed it! :facepalm:
also good call with comments in the child chunks👍
