### ISSUE TITLE
Add special unparseable message for curly quotes (and other Unicode characters?)

### ISSUE THREAD

**Issue by rossellhayes** [rstudio/learnr#639]
Currently, all unparseable user input returns the following message:

> It looks like this might not be valid R code. R cannot determine how to turn your text into a complete command. You may have forgotten to fill in a blank, to remove an underscore, to include a comma between arguments, or to close an opening <code>&quot;</code>, <code>'</code>, <code>(</code> or <code>{</code> with a matching <code>&quot;</code>, <code>'</code>, <code>)</code> or <code>}</code>.

This works well for code the student has typed incorrectly, but doesn't help with another common problem: students copying and pasting code with automatic Unicode formatting.

For example, if the code `str_detect("test", "t.+t")` is copied into Zoom chat, it will be reformatted with curly quotes as `str_detect(“test”, “t.+t”)`. The student may never notice the change, and be confused that their code is returning an error.

I propose adding the following messages to be displayed when a student's code is unparseable and contains a non-ASCII character.

#### Code with curly quotes
> It looks like this might not be valid R code. Your code contains curly quotation marks (“”) when R expects straight quotation marks (""). This can happen when you copy and paste code from another source. Try deleting the quotation marks in your code and retyping them manually.

#### Code with other non-ASCII characters

In this case, a student has copied a Unicode minus sign instead of an ASCII [hyphen-minus](https://en.wikipedia.org/wiki/Hyphen-minus):
> It looks like this might not be valid R code. Your code contains the following special character: −. Sometimes your code may contain a special character that looks like a regular character, especially if you copy and paste from another source. Try deleting the special character from your code and retyping it manually.

**Comment by dcossyleon** [comment]
This is great, @rossellhayes. 

What if `"Your code contains the following special character..."` was moved up to be the first line of the message? 

This way it could be easily differentiated at a glance from the default error message users will see more frequently when they have unparseable code due to typos, etc. My concern is that if the first lines of common and special cases are the same, the user may become habituated to this opener, assume it is always the default message, and miss the most important part of the feedback.

**Comment by rossellhayes** [comment]
@dcossyleon Great point. Do you think it would be fine to just remove the "It looks like this might not be valid R code" line?

**Comment by dtkaplan** [comment]
How about offering a best guess at what the un-Unicoded command would be.
So the message would read:

> It looks like your command was pasted from a source like Zoom or Word
that has formatted it with characters not allowed in R. Between the << and
>> marks is a version that replaces the un-allowed characters:  <<     str_detect("test",
"t.+t")     >>. Try cutting and pasting this new version into your session.
Of course, we can't guarantee that there aren't other problems with the
command or that it does what you want it to do.

**Comment by gadenbuie** [comment]
I like both suggestions from @dcossyleon and @dtkaplan. On the one hand, let's lead with the specific problem and then explain that those characters make the entered code invalid R syntax. I also think we could offer a fix where possible. So that it doesn't get out of hand I think it would be best to isolate the line with the invalid character, replace the characters and then format as a code block. 

Another idea would be to include a lintr-style code highlight, either in plaintext style

```r
str_detect(“test”, “t.+t”)
#          ^~~~~~~~~~~~~~~
```

or using HTML

```html
<pre><code>str_detect(<mark>“</mark>test<mark>”</mark>, <mark>“</mark>t.+t<mark>”</mark>)</code></pre>
```

![image](https://user-images.githubusercontent.com/5420529/150154751-c1f1520a-6d29-4696-a753-b86b068669b0.png)

So the end result would be a message like this:

> It looks like your code contains curly quotation marks (`“` or `”`) around character strings, making your code invalid. R requires character values to be contained in straight quotation marks (`"` or `'`). 
> 
> ```r
> str_detect(“test”, “t.+t”)
>            ^~~~~~~~~~~~~~~
> ```
>
> Don't worry, this is a common source of errors when you copy code from another app that applies its own formatting to text. You can try replacing line 1 with this code:
>
> ```r
> str_detect("test", "t.+t")
> ```

Or for generic unicode issues

> It looks like your R code contains an unexpected special character: `–` that makes your R code invalid. 
>
> ```r
> 63 – 21
>    ^~~~
> ```
> Sometimes your code may contain a special character that looks like a regular character, especially if you copy and paste the code from another app. Try deleting the special character from your code and retyping it manually.
